apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 6
  labels:
    app: eks-sample-linux-app
  name: eks-sample-linux-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eks-sample-linux-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eks-sample-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - args:
            - -c
            - sleep infinity
          command:
            - /bin/sh
          image: public.ecr.aws/ubuntu/ubuntu:22.04_stable
          imagePullPolicy: IfNotPresent
          name: linux
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k8s-svc2
      serviceAccountName: k8s-svc2
      terminationGracePeriodSeconds: 30
